name: HeathClassicMazda
layout_spectrum: 0.5423647444695234
typography_spectrum: 0.768381469650194
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8888391354121268
  lightness: 0.7164605141151696
  saturation: 0.7645150984171778
  rhythmicContrast: 0.3323907221201807
title: Using Social Media To Connect My Customers
author:
  name: Heath Patterson
  url: HeathClassicMazda.com
  email: HeathClassicMazda@gmail.com
content_rating:
  adult: false
